import type {
  AppointmentPreview,
  AppointmentType,
  AvailabilityPreview,
} from "./types"

export const appointmentTypes: AppointmentType[] = [
  {
    id: "first-visit",
    name: "Prima visita specialistica",
    specialty: "Medicina interna",
    duration: 45,
    price: 120,
    color: "#087f48",
    bookingMode: "both",
    paymentPolicy: "deposit",
    professionals: ["Dott.ssa Bianchi", "Dott. Romano"],
    minimumNotice: "24 ore",
    bufferBefore: 5,
    bufferAfter: 10,
  },
  {
    id: "follow-up",
    name: "Visita di controllo",
    specialty: "Medicina interna",
    duration: 30,
    price: 75,
    color: "#2889a7",
    bookingMode: "both",
    paymentPolicy: "optional",
    professionals: ["Dott.ssa Bianchi", "Dott. Romano", "Dott.ssa Neri"],
    minimumNotice: "12 ore",
    bufferBefore: 0,
    bufferAfter: 5,
  },
  {
    id: "teleconsult",
    name: "Teleconsulto",
    specialty: "Consulenza da remoto",
    duration: 25,
    price: 60,
    color: "#c17c33",
    bookingMode: "public",
    paymentPolicy: "required",
    professionals: ["Dott. Romano"],
    minimumNotice: "4 ore",
    bufferBefore: 0,
    bufferAfter: 5,
  },
  {
    id: "nursing",
    name: "Prestazione infermieristica",
    specialty: "Ambulatorio",
    duration: 20,
    price: null,
    color: "#74716a",
    bookingMode: "staff",
    paymentPolicy: "none",
    professionals: ["Elisa Conti"],
    minimumNotice: "Nessun limite",
    bufferBefore: 0,
    bufferAfter: 0,
  },
]

export const appointments: AppointmentPreview[] = [
  {
    id: "apt-1048",
    time: "09:00",
    patient: "Elena Martini",
    type: "Prima visita specialistica",
    professional: "Dott.ssa Bianchi",
    room: "Studio 2",
    status: "arrived",
    paymentStatus: "paid",
    amount: 120,
  },
  {
    id: "apt-1051",
    time: "10:15",
    patient: "Marco Riva",
    type: "Visita di controllo",
    professional: "Dott. Romano",
    room: "Studio 1",
    status: "confirmed",
    paymentStatus: "due",
    amount: 75,
  },
  {
    id: "apt-1054",
    time: "11:30",
    patient: "Anna Bellini",
    type: "Teleconsulto",
    professional: "Dott. Romano",
    room: "Online",
    status: "confirmed",
    paymentStatus: "paid",
    amount: 60,
  },
  {
    id: "apt-1059",
    time: "14:00",
    patient: "Luca Greco",
    type: "Prestazione infermieristica",
    professional: "Elisa Conti",
    room: "Ambulatorio",
    status: "pending",
    paymentStatus: "not-required",
    amount: null,
  },
]

export const availability: AvailabilityPreview[] = [
  {
    professional: "Giulia Bianchi",
    role: "Medico internista",
    initials: "GB",
    days: {
      Lun: "09:00–13:00",
      Mar: "14:00–19:00",
      Mer: "09:00–13:00",
      Gio: "14:00–19:00",
      Ven: "09:00–13:00",
    },
    exception: "Ferie giovedì 10",
  },
  {
    professional: "Paolo Romano",
    role: "Medico internista",
    initials: "PR",
    days: {
      Lun: "14:00–19:00",
      Mar: "09:00–13:00",
      Mer: "14:00–19:00",
      Gio: "09:00–13:00",
      Ven: "14:00–18:00",
    },
  },
  {
    professional: "Elisa Conti",
    role: "Infermiera",
    initials: "EC",
    days: {
      Lun: "08:30–16:30",
      Mar: "08:30–16:30",
      Mer: "08:30–16:30",
      Gio: "08:30–16:30",
      Ven: "08:30–14:30",
    },
  },
]
